[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  headers = {Content-Type = "application/javascript"}

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200
  headers = {Content-Type = "text/css"}

[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200
  headers = {Content-Type = "application/javascript"}

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  headers = {Content-Type = "application/javascript", Cache-Control = "no-cache"}

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  headers = {Content-Type = "application/manifest+json"}

# --- SPA Fallback for Single Page Application (React/Vite) ---
# This redirect ensures that all unknown routes are served index.html, enabling client-side routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# --- End SPA Fallback ---

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"