
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ffnitxyrkbujxiascdik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmbml0eHlya2J1anhpYXNjZGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjAwMjQsImV4cCI6MjA3MDgzNjAyNH0.MP88l8wDK0N6Mksg5BtWMiioybC8_awtV0M0eX5ENww";

// Validate configuration
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Supabase configuration missing. Please check your environment variables.');
}

console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key configured:', SUPABASE_PUBLISHABLE_KEY ? 'Yes' : 'No');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    }
  }
});
